# looking to see whether Q val correlates with n mods
library(dplyr)
setwd('~/Documents/workspace/steadystate_data/')
qq <- read.csv('q_nmod_corr.csv')
qq2 <- stack(qq[,2:5])
qq3_df <- tbl_df(data.frame(qq2, as.factor(rep(seq(19), 4))))
colnames(qq3_df) <- c('values', 'condition', 'subj')
# print(summary(aov(values ~ condition + Error(subj/condition), data = qq3_df)))
attach(qq3_df)
# print(friedman.test(values ~ condition | subj))
sink('q_nmod_corr_report.txt')
print(tapply(values, condition, mean))
print('Overall mean: ')
print(mean(values))
sink()
